# Pruebas con Pytest

Mejore la experiencia de pruebas con Pytest, una excelente opci√≥n para escribir, ejecutar y ampliar pruebas en Python. Exp√≥ngase a patrones √∫tiles y a los conceptos b√°sicos de las pruebas con Pytest.

üîó [Microsoft Learn](https://learn.microsoft.com/es-es/training/modules/test-python-with-pytest/)

### Objetivos de aprendizaje:

* Escribir pruebas mediante `pytest`, uno de los marcos de pruebas m√°s populares para Python
* Acostumbrarse a los potentes informes en los errores de las pruebas.
* Usar funciones, clases y m√©todos para las pruebas

<hr/>

## Introducci√≥n

La introducci√≥n a las pruebas en Python puede ser abrumadora. La biblioteca est√°ndar de Python ofrece utilidades y asistentes para escribir pruebas, pero con algunos inconvenientes que podr√≠an hacerlo dif√≠cil.

Pytest es una de las herramientas y marcos de pruebas m√°s populares para Python. Aunque Pytest puede ayudar con escenarios de pruebas muy complejos, no fuerza sus funcionalidades al crear pruebas. Puede escribir pruebas muy sencillas y seguir benefici√°ndose del ejecutor de pruebas r√°pido y con caracter√≠sticas y de informes √∫tiles.

Un aspecto crucial de Pytest es que facilita mucho la escritura de pruebas. Puede escribir una funci√≥n de prueba sin dependencias ni configuraci√≥n y ejecutar la prueba inmediatamente.

En este m√≥dulo se tratar√°n algunos de los conceptos b√°sicos necesarios para empezar a trabajar con Pytest y poder llevar el conjunto de pruebas al siguiente nivel.

<hr/>

## Conceptos b√°sicos de Pytest

Comencemos a realizar pruebas con Pytest. Como hemos mencionado antes, Pytest es altamente configurable y puede controlar conjuntos de pruebas complejos. Pero no requiere muchos conocimientos para empezar a escribir pruebas. De hecho, cuanto m√°s sencillo sea escribir pruebas en un marco, mejor.

Al final de esta secci√≥n, tendr√° todo lo que necesita para empezar a escribir las primeras pruebas y ejecutarlas con Pytest.

### Convenciones

Antes de profundizar en la escritura de pruebas, debemos cubrir algunas de las convenciones de prueba en las que se basa Pytest.

No hay reglas dif√≠ciles sobre archivos de prueba, directorios de prueba o dise√±os de pruebas generales en Python. Al conocer estas reglas, puede aprovechar la detecci√≥n y ejecuci√≥n autom√°ticas de pruebas sin necesidad de ninguna configuraci√≥n adicional.

#### Archivos de prueba y directorio de pruebas

El directorio principal de las pruebas es el directorio tests. Puede colocar este directorio en el nivel ra√≠z del proyecto, pero tampoco es inusual verlo junto con los m√≥dulos de c√≥digo.

> ‚ÑπÔ∏è **Nota** <br/>
> En este m√≥dulo, usaremos de forma predeterminada *tests* en la ra√≠z de un proyecto.

Veamos c√≥mo se ve la ra√≠z de un peque√±o proyecto de Python denominado *jformat*:

```text
.
‚îú‚îÄ‚îÄ README.md
‚îú‚îÄ‚îÄ jformat
‚îÇ¬†¬† ‚îú‚îÄ‚îÄ __init__.py
‚îÇ¬†¬† ‚îî‚îÄ‚îÄ main.py
‚îú‚îÄ‚îÄ setup.py
‚îî‚îÄ‚îÄ tests
    ‚îî‚îÄ‚îÄ test_main.py
```

El directorio *tests* se encuentra en la ra√≠z del proyecto con un √∫nico archivo de prueba. En este caso, el archivo de prueba se denomina *test_main.py*. Estas son dos convenciones cr√≠ticas:

* Uso de un directorio *tests* para colocar archivos de prueba y directorios de pruebas anidados
* Prefijo de archivos de prueba con *test*. El prefijo indica que el archivo contiene c√≥digo de prueba.

> ‚ùå **Precauci√≥n** <br/>
> Evite usar `test` (forma singular) como nombre de directorio. El nombre `test` es un m√≥dulo de Python, por lo que la creaci√≥n de un directorio con el mismo nombre lo invalidar√≠a. Use siempre el plural *tests* en su lugar.

#### Funciones de prueba

Uno de los argumentos fuertes para usar Pytest es que permite escribir funciones de prueba. De forma similar a los archivos de prueba, la funci√≥n debe tener el prefijo `test_`. Con el prefijo `test_`, se asegurar√° de que Pytest recopila la prueba y la ejecuta.

A continuaci√≥n se muestra el aspecto de una funci√≥n de prueba sencilla:

```Python
def test_main():
    assert "a string value" == "a string value"
```

#### Clases de prueba y m√©todos de prueba

De forma similar a las convenciones ya mencionadas, las clases de prueba y los m√©todos deben tener el prefijo `test`.

De la misma manera que otras convenciones de nomenclatura en Python para clases y m√©todos, se muestra c√≥mo ser√≠a una clase de prueba peque√±a que compruebe los nombres de usuario en una aplicaci√≥n:

```Python
class TestUser:

    def test_username(self):
        assert default() == "default username"
```

Esta es una diferencia principal con la biblioteca `unittest` de Python: no es necesario realizar ninguna herencia. Estas son las convenciones adicionales:

* Las clases de prueba tienen el prefijo `Test`
* Los m√©todos de prueba tienen el prefijo `test_`

### Ejecutar pruebas

Pytest es a la vez un marco de pruebas y un ejecutor de pruebas. El ejecutor de pruebas es un ejecutable en la l√≠nea de comandos que, a nivel alto, puede:

* Realizar la recopilaci√≥n de pruebas, buscar todos los archivos de prueba, las clases de prueba y las funciones de prueba para una ejecuci√≥n de prueba
* Iniciar una ejecuci√≥n de pruebas mediante la ejecuci√≥n de todas las pruebas
* Realizar un seguimiento de los errores y superar pruebas
* Proporcionar informes completos al final de una ejecuci√≥n de prueba

> ‚ÑπÔ∏è **Nota** <br/>
> Dado que Pytest es una biblioteca externa, se *debe* instalar para poder usarse.

Dados estos contenidos en un archivo *test_main.py*, podemos ver c√≥mo se comporta Pytest mediante la ejecuci√≥n de las pruebas:

```Python
# contents of test_main.py file

def test_main():
    assert True
```

En la l√≠nea de comandos, en la misma ruta de acceso donde existe el archivo *test_main.py*, podemos ejecutar el ejecutable `pytest`:

```Bash
$ pytest
=========================== test session starts ============================
Python 3.10.9, pytest-7.3.1, pluggy-1.0.0
collected 1 item

tests\test_main.py .                                                  [100%]

============================ 1 passed in 0.00s =============================
```

En segundo plano, Pytest recopil√≥ la prueba de ejemplo en el archivo de prueba sin necesidad de configuraci√≥n.

#### Instrucci√≥n de aserci√≥n eficaz

Como es posible que ya haya observado, todos los ejemplos de prueba usan la llamada sin formato `assert`. Normalmente, en Python, la instrucci√≥n `assert` no se usa para las pruebas porque carece de informes adecuados cuando se produce un error en la aserci√≥n. Sin embargo, al usar Pytest, este no es el caso. En segundo plano, Pytest permite que la instrucci√≥n realice comparaciones enriquecidas sin forzar al usuario a escribir m√°s c√≥digo ni configurar nada.

Mediante la instrucci√≥n sin formato `assert`, puede usar los operadores de Python. Por ejemplo, `>`, `<`, `!=`, `>=` o `<=`. Todos los operadores de Python son v√°lidos. Esta funcionalidad puede ser la caracter√≠stica m√°s crucial de Pytest: no es necesario aprender una nueva sintaxis para escribir aserciones.

Veamos c√≥mo se traduce al tratar con comparaciones comunes con objetos de Python. En este caso, vamos a pasar por el informe de errores al comparar cadenas muy largas:

```Bash
================================= FAILURES =================================
____________________________ test_long_strings _____________________________

    def test_long_strings():
        left = "this is a very long strings to be compared with another long string"
        right = "This is a very long string to be compared with another long string"
>       assert left == right
E       AssertionError: assert 'this is a ve...r long string' == 'This is a ve...r long string'
E         - This is a very long string to be compared with another long string
E         ? ^
E         + this is a very long strings to be compared with another long string
E         ? ^                         +

test_main.py:4: AssertionError
```

Pytest muestra contexto √∫til entorno al error. Un uso de may√∫sculas y min√∫sculas incorrectos al principio de la cadena y un car√°cter adicional en una palabra. Pero m√°s all√° de las cadenas, Pytest puede ayudar con otros objetos y estructuras de datos. As√≠ se comporta con las listas:

```Bash
________________________________ test_lists ________________________________

    def test_lists():
        left = ["sugar", "wheat", "coffee", "salt", "water", "milk"]
        right = ["sugar", "coffee", "wheat", "salt", "water", "milk"]
>       assert left == right
E       AssertionError: assert ['sugar', 'wh...ater', 'milk'] == ['sugar', 'co...ater', 'milk']
E         At index 1 diff: 'wheat' != 'coffee'
E         Full diff:
E         - ['sugar', 'coffee', 'wheat', 'salt', 'water', 'milk']
E         ?                     ---------
E         + ['sugar', 'wheat', 'coffee', 'salt', 'water', 'milk']
E         ?           +++++++++

test_main.py:9: AssertionError
```

Este informe identifica que el √≠ndice 1 (segundo elemento de la lista) es diferente. No solo identifica el n√∫mero de √≠ndice, sino que tambi√©n proporciona una representaci√≥n del error. Aparte de las comparaciones de elementos, tambi√©n puede notificar si faltan elementos y proporcionar informaci√≥n que puede indicar exactamente qu√© elemento podr√≠a ser. En el siguiente caso, es `"milk"`:

```Bash
________________________________ test_lists ________________________________

    def test_lists():
        left = ["sugar", "wheat", "coffee", "salt", "water", "milk"]
        right = ["sugar", "wheat", "salt", "water", "milk"]
>       assert left == right
E       AssertionError: assert ['sugar', 'wh...ater', 'milk'] == ['sugar', 'wh...ater', 'milk']
E         At index 2 diff: 'coffee' != 'salt'
E         Left contains one more item: 'milk'
E         Full diff:
E         - ['sugar', 'wheat', 'salt', 'water', 'milk']
E         + ['sugar', 'wheat', 'coffee', 'salt', 'water', 'milk']
E         ?                    ++++++++++

test_main.py:9: AssertionError
```

Por √∫ltimo, veamos c√≥mo se comporta con los diccionarios. Comparar dos diccionarios grandes puede ser abrumador si hay errores, pero Pytest realiza un trabajo sobresaliente al proporcionar contexto e identificar el error:

```Bash
____________________________ test_dictionaries _____________________________

    def test_dictionaries():
        left = {"street": "Ferry Ln.", "number": 39, "state": "Nevada", "zipcode": 30877, "county": "Frett"}
        right = {"street": "Ferry Lane", "number": 38, "state": "Nevada", "zipcode": 30877, "county": "Frett"}
>       assert left == right
E       AssertionError: assert {'county': 'F...rry Ln.', ...} == {'county': 'F...ry Lane', ...}
E         Omitting 3 identical items, use -vv to show
E         Differing items:
E         {'street': 'Ferry Ln.'} != {'street': 'Ferry Lane'}
E         {'number': 39} != {'number': 38}
E         Full diff:
E           {
E            'county': 'Frett',...
E
E         ...Full output truncated (12 lines hidden), use '-vv' to show
```

En esta prueba, hay dos errores en el diccionario. Uno es que el valor `"street"` es diferente y el otro es que `"number"` no coincide.

Pytest detecta con precisi√≥n estas diferencias (aunque se trata de un error en una sola prueba). Dado que los diccionarios contienen muchos elementos, Pytest omite las partes id√©nticas y solo muestra contenido relevante. Veamos lo que sucede si hacemos uso de la marca `-vv` sugerida para aumentar el nivel de detalle en el resultado:

```Bash
____________________________ test_dictionaries _____________________________

    def test_dictionaries():
        left = {"street": "Ferry Ln.", "number": 39, "state": "Nevada", "zipcode": 30877, "county": "Frett"}
        right = {"street": "Ferry Lane", "number": 38, "state": "Nevada", "zipcode": 30877, "county": "Frett"}
>       assert left == right
E       AssertionError: assert {'county': 'Frett',\n 'number': 39,\n 'state': 'Nevada',\n 'street': 'Ferry Ln.',\n 'zipcode': 30877} == {'county': 'Frett',\n 'number': 38,\n 'state': 'Nevada',\n 'street': 'Ferry Lane',\n 'zipcode': 30877}
E         Common items:
E         {'county': 'Frett', 'state': 'Nevada', 'zipcode': 30877}
E         Differing items:
E         {'number': 39} != {'number': 38}
E         {'street': 'Ferry Ln.'} != {'street': 'Ferry Lane'}
E         Full diff:
E           {
E            'county': 'Frett',
E         -  'number': 38,
E         ?             ^
E         +  'number': 39,
E         ?             ^
E            'state': 'Nevada',
E         -  'street': 'Ferry Lane',
E         ?                    - ^
E         +  'street': 'Ferry Ln.',
E         ?                     ^
E            'zipcode': 30877,
E           }
```

Al ejecutar `pytest -vv`, el informe aumenta la cantidad de detalles y proporciona una comparaci√≥n pormenorizada. No solo este informe detecta y muestra el error, sino que le permite realizar r√°pidamente cambios para corregir el problema.

<hr/>

## Clases y m√©todos de prueba

Adem√°s de escribir funciones de prueba, Pytest permite el uso de clases. Como ya hemos mencionado, no es necesaria la herencia y las clases de prueba siguen algunas reglas sencillas. El uso de clases proporciona m√°s flexibilidad y reutilizaci√≥n. Como ver√° a continuaci√≥n, Pytest se mantiene fuera del camino y evita forzarle a escribir pruebas de una manera determinada.

Al igual que las funciones, todav√≠a puede escribir aserciones mediante la instrucci√≥n `assert`.

### Compilaci√≥n de una clase de prueba

Vamos a usar un escenario real para ver c√≥mo pueden ayudar las clases de prueba. La siguiente funci√≥n comprueba si un archivo determinado tiene un contenido de "yes" para devolver `True`. Si el archivo no existe o si contiene un "no", devuelve `False`. Este escenario es com√∫n en las tareas asincr√≥nicas que usan el sistema de archivos para indicar la finalizaci√≥n.

Este es el aspecto de la funci√≥n:

```Python
import os

def is_done(path):
    if not os.path.exists(path):
        return False
    with open(path) as _f:
        contents = _f.read()
    if "yes" in contents.lower():
        return True
    elif "no" in contents.lower():
        return False
```

Este es el aspecto de una clase con dos pruebas (una para cada condici√≥n) en un archivo denominado *test_files.py*:

```Python
class TestIsDone:

    def test_yes(self):
        with open("/tmp/test_file", "w") as _f:
            _f.write("yes")
        assert is_done("/tmp/test_file") is True

    def test_no(self):
        with open("/tmp/test_file", "w") as _f:
            _f.write("no")
        assert is_done("/tmp/test_file") is False
```

> ‚ùå **Precauci√≥n** <br/>
> Los m√©todos de prueba usan la ruta de acceso */tmp* para un archivo de prueba temporal porque es m√°s f√°cil de usar para el ejemplo. Sin embargo, si necesita usar archivos temporales, considere la posibilidad de usar una biblioteca como `tempfile` que pueda crearlos (y quitarlos) de forma segura. No todos los sistemas tienen un directorio */tmp* y esa ubicaci√≥n podr√≠a no ser temporal en funci√≥n del sistema operativo.

La ejecuci√≥n de las pruebas con la marca `-v` para aumentar el nivel de detalle muestra las pruebas superadas:

```Bash
pytest -v test_files.py
============================= test session starts ==============================
Python 3.10.9, pytest-7.3.1, pluggy-1.0.0
rootdir: /private
cachedir: .pytest_cache
collected 2 items

test_files.py::TestIsDone::test_yes PASSED                               [ 50%]
test_files.py::TestIsDone::test_no PASSED                                [100%]

============================== 2 passed in 0.00s ===============================
```

Aunque se superan las pruebas, parecen algo repetitivas y tambi√©n dejan archivos una vez finalizada la prueba. Antes de ver c√≥mo podemos mejorar esto, vamos a tratar los m√©todos auxiliares en la secci√≥n siguiente.

### M√©todos auxiliares

En una clase de prueba, hay algunos m√©todos que puede usar para configurar y anular la ejecuci√≥n de pruebas. Pytest los ejecutar√° autom√°ticamente si as√≠ se define. Para usar estos m√©todos, debe saber que tienen un orden y un comportamiento espec√≠ficos.

* `setup`: se ejecuta una vez antes de cada prueba en una clase.
* `teardown`: se ejecuta una vez despu√©s de cada prueba en una clase.
* `setup_class`: se ejecuta una vez antes de todas las pruebas en una clase.
* `teardown_class`: se ejecuta una vez despu√©s de todas las pruebas en una clase.

Le resultar√° √∫til escribir m√©todos de configuraci√≥n cuando las pruebas requieran recursos similares (o id√©nticos) para funcionar. Lo ideal es que una prueba no deje recursos cuando se complete, por lo que los m√©todos de anulaci√≥n pueden ayudar en la limpieza de pruebas en esas situaciones.

#### Limpieza

Vamos a comprobar una clase de prueba actualizada que limpia los archivos despu√©s de cada prueba:

```Python
class TestIsDone:

    def teardown(self):
        if os.path.exists("/tmp/test_file"):
            os.remove("/tmp/test_file")

    def test_yes(self):
        with open("/tmp/test_file", "w") as _f:
            _f.write("yes")
        assert is_done("/tmp/test_file") is True

    def test_no(self):
        with open("/tmp/test_file", "w") as _f:
            _f.write("no")
        assert is_done("/tmp/test_file") is False
```

Con el m√©todo `teardown()`, esta clase de prueba ya no dejar√° atr√°s un archivo */tmp/test_file*.

#### Configurar

Otra mejora que podemos hacer en esta clase es agregar una variable que apunte al archivo. Puesto que el archivo se declara ahora en seis lugares, cualquier cambio en la ruta de acceso significar√≠a cambiarlo en todos esos puntos. Este es el aspecto de la clase con un m√©todo `setup()` agregado que declara la variable de ruta de acceso:

```Python
class TestIsDone:

    def setup(self):
        self.tmp_file = "/tmp/test_file"

    def teardown(self):
        if os.path.exists(self.tmp_file):
            os.remove(self.tmp_file)

    def test_yes(self):
        with open(self.tmp_file, "w") as _f:
            _f.write("yes")
        assert is_done(self.tmp_file) is True

    def test_no(self):
        with open(self.tmp_file, "w") as _f:
            _f.write("no")
        assert is_done(self.tmp_file) is False
```

#### M√©todos del asistente personalizados

Puede crear m√©todos del asistente personalizados en una clase. Estos m√©todos no deben tener el prefijo con el nombre `test` y no se pueden denominar como los m√©todos de configuraci√≥n o limpieza. En la clase `TestIsDone`, podr√≠amos automatizar la creaci√≥n del archivo temporal en un asistente personalizado. Este es el aspecto que podr√≠a tener el m√©todo auxiliar:

```Python
def write_tmp_file(self, content):
        with open(self.tmp_file, "w") as _f:
            _f.write(content)
```

Pytest no ejecutar√° autom√°ticamente el m√©todo `write_tmp_file()` y otros m√©todos pueden llamarlo directamente para ahorrarse la realizaci√≥n de tareas repetitivas como escribir en un archivo.

Este es el aspecto de toda la clase despu√©s de actualizar los m√©todos de prueba para usar el asistente personalizado:

```Python
class TestIsDone:

    def setup(self):
        self.tmp_file = "/tmp/test_file"

    def teardown(self):
        if os.path.exists(self.tmp_file):
            os.remove(self.tmp_file)

    def write_tmp_file(self, content):
        with open(self.tmp_file, "w") as _f:
            _f.write(content)

    def test_yes(self):
        self.write_tmp_file("yes")
        assert is_done(self.tmp_file) is True

    def test_no(self):
        self.write_tmp_file("no")
        assert is_done(self.tmp_file) is False
```

### Cu√°ndo usar una clase en lugar de una funci√≥n

No hay reglas estrictas en cuanto a cu√°ndo usar una clase en lugar de una funci√≥n. Siempre es buena idea seguir las convenciones de los proyectos y equipos actuales con los que trabaja, pero estas son algunas ideas generales que puede usar para determinar cu√°ndo usar una clase.

* Cuando las pruebas necesitan una configuraci√≥n o limpieza similares
* Cuando tiene sentido agruparlos
* Si hay al menos varias pruebas
* Cuando las pruebas pueden beneficiarse de un conjunto com√∫n de asistentes

<hr/>

## Ejercicio

En este ejercicio, usar√° Pytest para probar una funci√≥n. A continuaci√≥n, encontrar√° y corregir√° algunos posibles problemas con la funci√≥n que provocan que las pruebas tengan errores. Examinar los errores y usar los informes de errores enriquecidos de Pytest es esencial para identificar y corregir errores o pruebas problem√°ticas en el c√≥digo de producci√≥n.

En este ejercicio, usaremos una funci√≥n denominada `admin_command()` que acepta un comando del sistema como entrada y, opcionalmente, le agrega un prefijo con la herramienta `sudo`. La funci√≥n tiene un error, que detectar√° escribiendo pruebas.

### Paso 1: Adici√≥n de un archivo con pruebas para este ejercicio

1. Cree un nuevo archivo de prueba usando las convenciones de nombre de archivo de Python para los archivos de prueba. Dele el nombre *test_exercise.py* al archivo de prueba y agregue el siguiente c√≥digo:

```Python
def admin_command(command, sudo=True):
    """
    Prefix a command with `sudo` unless it is explicitly not needed. Expects `command` to be a list.
    """
    if sudo:
        ["sudo"] + command
    return command
```

La funci√≥n `admin_command()` toma una lista como entrada mediante el argumento `command` y, opcionalmente, puede agregar un prefijo a la lista con `sudo`. Si el argumento de palabra clave `sudo` se establece en `False`, devuelve el mismo comando especificado como entrada.

2. En el mismo archivo, anexe las pruebas para la funci√≥n `admin_command()`. Las pruebas usan un m√©todo auxiliar que devuelve un comando de ejemplo:

```Python
class TestAdminCommand:

def command(self):
    return ["ps", "aux"]

def test_no_sudo(self):
    result = admin_command(self.command(), sudo=False)
    assert result == self.command()

def test_sudo(self):
    result = admin_command(self.command(), sudo=True)
    expected = ["sudo"] + self.command()
    assert result == expected
```
 
> ‚ÑπÔ∏è **Nota** <br/>
> No es habitual tener pruebas dentro del mismo archivo como c√≥digo real. Por motivos de simplicidad, los ejemplos de este ejercicio tendr√°n c√≥digo real en el mismo archivo. En los proyectos de Python reales, descubrir√° que las pruebas est√°n separadas por archivos y directorios del c√≥digo que est√° probando.

### Paso 2: Ejecuci√≥n de las pruebas e identificaci√≥n del error

Ahora que el archivo de prueba tiene una funci√≥n para probarla y un par de pruebas para comprobar su comportamiento, es el momento de ejecutar las pruebas y trabajar con errores.

* Ejecute el archivo con Python:

```Bash
$ pytest test_exercise.py
```

La ejecuci√≥n debe completarse con la superaci√≥n de una prueba y un error, y la salida del error debe ser similar a la siguiente:

```Bash
=================================== FAILURES ===================================
__________________________ TestAdminCommand.test_sudo __________________________

self = <test_exercise.TestAdminCommand object at 0x10634c2e0>

    def test_sudo(self):
        result = admin_command(self.command(), sudo=True)
        expected = ["sudo"] + self.command()
>       assert result == expected
E       AssertionError: assert ['ps', 'aux'] == ['sudo', 'ps', 'aux']
E         At index 0 diff: 'ps' != 'sudo'
E         Right contains one more item: 'aux'
E         Use -v to get the full diff

test_exercise.py:24: AssertionError
=========================== short test summary info ============================
FAILED test_exercise.py::TestAdminCommand::test_sudo - AssertionError: assert...
========================= 1 failed, 1 passed in 0.04s ==========================
```

El resultado produce un error en la prueba `test_sudo()`. Pytest proporciona detalles sobre las dos listas que se comparan. En este caso, la variable `result` no contiene el comando `sudo`, que es lo que espera la prueba.

### Paso 3: Correcci√≥n del error y superaci√≥n de las pruebas

Antes de realizar cambios, debe comprender por qu√© hay un error en primer lugar. Aunque sabemos que no se cumple la expectativa (`sudo` no est√° en el resultado), debe averiguar por qu√©.

Examine las siguientes l√≠neas de c√≥digo de la funci√≥n `admin_command()` cuando se cumpla la condici√≥n `sudo=True`:

```Python
if sudo:
    ["sudo"] + command
```

La operaci√≥n de las listas no se usa para devolver el valor. Puesto que no se devuelve, la funci√≥n termina devolviendo siempre el comando sin `sudo`.

1. Actualice la funci√≥n `admin_command()` para que devuelva la operaci√≥n de lista de modo que se use el resultado modificado al solicitar un comando `sudo`. La funci√≥n actualizada debe tener este aspecto:

```Python
def admin_command(command, sudo=True):
    """
    Prefix a command with `sudo` unless it is explicitly not needed. Expects `command` to be a list.
    """
    if sudo:
        return ["sudo"] + command
    return command
```

2. Vuelva a ejecutar la prueba con Pytest. Intente aumentar el nivel de detalle de la salida mediante la marca `-v` con Pytest:

```Bash
$ pytest -v test_exercise.py
```

3. Compruebe la salida. Ahora deber√≠a mostrar que se superan dos pruebas:

```Bash
============================= test session starts ==============================
Python 3.10.9, pytest-7.3.1, pluggy-1.0.0
rootdir: /private
collected 2 items

test_exercise.py::TestAdminCommand::test_no_sudo PASSED                  [ 50%]
test_exercise.py::TestAdminCommand::test_sudo PASSED                     [100%]

============================== 2 passed in 0.00s ===============================
```

> ‚ÑπÔ∏è **Nota** <br/>
> Puesto que la funci√≥n admite m√°s valores con diferentes usos de may√∫sculas y min√∫sculas, se deben agregar m√°s pruebas para cubrir esas variantes. Esto impedir√≠a que, en el futuro, los cambios que se realicen en la funci√≥n den lugar a un comportamiento diferente (inesperado).

### Paso 4: Adici√≥n de c√≥digo nuevo con pruebas

Ahora que ha agregado pruebas, debe sentirse c√≥modo teniendo m√°s cambios en la funci√≥n y comprobarlos con pruebas. Incluso si los cambios no est√°n cubiertos por las pruebas existentes, puede sentirse seguro de que no est√° rompiendo ninguna suposici√≥n anterior.

En este caso, la funci√≥n `admin_command()` conf√≠a ciegamente en que el argumento `command` siempre es una lista. Vamos a mejorarlo asegur√°ndose de que se genera una excepci√≥n con un mensaje de error √∫til.

1. En primer lugar, cree una prueba que capture el comportamiento. Aunque la funci√≥n a√∫n no se ha actualizado, primero probar√° un enfoque de prueba (tambi√©n conocido como Desarrollo controlado por pruebas o TDD).

    - Actualice el archivo test_exercise.py para que importe pytest en la parte superior. Esta prueba usar√° un asistente interno del marco de trabajo pytest:

    ```Python
    import pytest
    ```

    - Ahora, anexe una nueva prueba a la clase para comprobar la excepci√≥n. Esta prueba debe esperar una `TypeError` de la funci√≥n cuando se pasa un valor que no es de lista a la funci√≥n:

    ```Python
    def test_non_list_commands(self):
        with pytest.raises(TypeError):
            admin_command("some command", sudo=True)
    ```

2. Vuelva a ejecutar las pruebas con Pytest. Todas se deben superar:

```Bash
============================= test session starts ==============================
Python 3.10.9, pytest-7.3.1, pluggy-1.0.0
rootdir: /private
collected 3 items

test_exercise.py ...                                                     [100%]

============================== 3 passed in 0.00s ===============================
```

La prueba es lo suficientemente buena para comprobar `TypeError`, pero ser√≠a bueno agregar el c√≥digo con un mensaje de error √∫til.

3. Actualice la funci√≥n para generar expl√≠citamente un `TypeError` con un mensaje de error √∫til:

```Python
def admin_command(command, sudo=True):
    """
    Prefix a command with `sudo` unless it is explicitly not needed. Expects `command` to be a list.
    """
    if not isinstance(command, list):
        raise TypeError(f"was expecting command to be a list, but got a {type(command)}")
    if sudo:
        return ["sudo"] + command
    return command
```

4. Por √∫ltimo, actualice el m√©todo `test_non_list_commands()` para comprobar el mensaje de error:

```Python
def test_non_list_commands(self):
    with pytest.raises(TypeError) as error:
        admin_command("some command", sudo=True)
    assert error.value.args[0] == "was expecting command to be a list, but got a <class 'str'>"
```

La prueba actualizada usa `error` como una variable que contiene toda la informaci√≥n de excepci√≥n. Con `error.value.args`, puede examinar los argumentos de la excepci√≥n. En este caso, el primer argumento tiene la cadena de error que la prueba puede comprobar.

### Comprobar el trabajo

Llegado a este punto, debe tener un archivo de prueba de Python con un nombre similar a test_exercise.py y los siguientes elementos:

* Una funci√≥n `admin_command()` que acepta un argumento y un argumento de palabra clave.
* Una excepci√≥n `TypeError` con un mensaje de error √∫til en la funci√≥n `admin_command()`.
* Una clase de prueba `TestAdminCommand()` que tiene un m√©todo auxiliar `command()` y tres m√©todos de prueba que comprueban la funci√≥n `admin_command()`.

Todas las pruebas deben superarse al ejecutarlas en el terminal, sin errores.